---
layout: default
---

title: My Sophomore AP Computer Science Website
theme: jekyll-theme-cayman
author: Lunat1cX
school_email: khrushkouski@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  My name is Konstantin Hrushkouski and the purpose of this website is to provide an image, my social media information, and a brag sheet.

# social links
twitter_username: Lunat1cOfficial
github_username:  Lunat1cX

show_excerpts: true # set to false to remove excerpts on the homepage
